using System;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Net.Http.Json;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;
using EnterpriseMediator.Financial.Domain.Entities;
using EnterpriseMediator.Financial.Domain.Interfaces;
using EnterpriseMediator.Financial.Infrastructure.Persistence.Configurations;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

namespace EnterpriseMediator.Financial.Infrastructure.Gateways.Wise
{
    /// <summary>
    /// Infrastructure adapter for the Wise (formerly TransferWise) Payout Gateway.
    /// Handles the creation of Quotes and Fund Transfers for vendor payouts via the Wise API.
    /// Implements the IPayoutGateway interface to keep the domain layer independent of Wise specifics.
    /// </summary>
    public class WisePayoutAdapter : IPayoutGateway
    {
        private readonly HttpClient _httpClient;
        private readonly WiseSettings _settings;
        private readonly ILogger<WisePayoutAdapter> _logger;

        // Wise API Endpoints
        private const string QuotesEndpoint = "v2/quotes";
        private const string TransfersEndpoint = "v1/transfers";
        private const string FundTransferEndpoint = "v3/profiles/{0}/transfers/{1}/payments";

        public WisePayoutAdapter(
            HttpClient httpClient,
            IOptions<WiseSettings> settings,
            ILogger<WisePayoutAdapter> logger)
        {
            _httpClient = httpClient ?? throw new ArgumentNullException(nameof(httpClient));
            _settings = settings?.Value ?? throw new ArgumentNullException(nameof(settings));
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));

            ValidateConfiguration();
            ConfigureHttpClient();
        }

        private void ValidateConfiguration()
        {
            if (string.IsNullOrWhiteSpace(_settings.ApiToken))
                throw new InvalidOperationException("Wise API Token is not configured.");
            
            if (_settings.ProfileId <= 0)
                throw new InvalidOperationException("Wise Profile ID is invalid.");

            if (string.IsNullOrWhiteSpace(_settings.BaseUrl))
                throw new InvalidOperationException("Wise Base URL is not configured.");
        }

        private void ConfigureHttpClient()
        {
            _httpClient.BaseAddress = new Uri(_settings.BaseUrl);
            _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", _settings.ApiToken);
            _httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
        }

        /// <summary>
        /// Executes a payout to a vendor by creating a quote and then a transfer in Wise.
        /// </summary>
        /// <param name="payout">The payout domain entity.</param>
        /// <param name="recipientAccountId">The Wise recipient ID for the vendor (must be pre-created/resolved).</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>The external Transfer ID generated by Wise.</returns>
        public async Task<string> ExecutePayoutAsync(Payout payout, string recipientAccountId, CancellationToken cancellationToken)
        {
            if (payout == null) throw new ArgumentNullException(nameof(payout));
            if (string.IsNullOrWhiteSpace(recipientAccountId)) throw new ArgumentNullException(nameof(recipientAccountId));

            _logger.LogInformation("Initiating Wise payout for PayoutId {PayoutId} to Recipient {RecipientId}.", payout.Id, recipientAccountId);

            try
            {
                // Step 1: Create a Quote to lock in the exchange rate (even if same currency) and fees.
                var quoteId = await CreateQuoteAsync(payout, recipientAccountId, cancellationToken);
                _logger.LogDebug("Wise Quote created: {QuoteId} for Payout {PayoutId}", quoteId, payout.Id);

                // Step 2: Create the Transfer using the Quote ID.
                var transferId = await CreateTransferAsync(payout, recipientAccountId, quoteId, cancellationToken);
                _logger.LogInformation("Wise Transfer created: {TransferId} for Payout {PayoutId}", transferId, payout.Id);

                // Note: Depending on the Wise account setup (pre-funded vs bank transfer), 
                // an explicit 'Fund' step might be required here. 
                // For this implementation, we assume a pre-funded business account where creation implies execution 
                // or creates a pending transfer that will be processed by Wise's batch system.
                // If explicit funding is needed:
                // await FundTransferAsync(transferId, cancellationToken);

                return transferId.ToString();
            }
            catch (HttpRequestException ex)
            {
                _logger.LogError(ex, "HTTP Error executing Wise payout for PayoutId {PayoutId}. Status: {StatusCode}", payout.Id, ex.StatusCode);
                throw new InvalidOperationException($"Wise Payout failed due to network or API error: {ex.Message}", ex);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Unexpected error executing Wise payout for PayoutId {PayoutId}.", payout.Id);
                throw;
            }
        }

        private async Task<string> CreateQuoteAsync(Payout payout, string targetAccount, CancellationToken ct)
        {
            var request = new
            {
                profile = _settings.ProfileId,
                sourceCurrency = payout.Amount.Currency.Code, // Assuming we pay out in the same currency we hold, or conversion happens here
                targetCurrency = payout.Amount.Currency.Code, // Target currency could be different, simplified here to same
                targetAmount = payout.Amount.Amount,
                payOut = "BALANCE" // Funding source
            };

            var response = await _httpClient.PostAsJsonAsync(QuotesEndpoint, request, ct);
            await EnsureSuccessAsync(response, "Create Quote");

            var result = await response.Content.ReadFromJsonAsync<WiseQuoteResponse>(cancellationToken: ct);
            return result?.Id ?? throw new InvalidOperationException("Failed to retrieve Quote ID from Wise response.");
        }

        private async Task<string> CreateTransferAsync(Payout payout, string recipientId, string quoteId, CancellationToken ct)
        {
            // Idempotency key ensures we don't double-pay if the network fails but Wise processed the request.
            var idempotencyKey = payout.Id.ToString(); 

            var request = new
            {
                targetAccount = recipientId,
                quoteUuid = quoteId,
                customerTransactionId = idempotencyKey,
                details = new
                {
                    reference = $"Payout-{payout.Id.ToString().Substring(0, 8)}", // Reference visible on bank statement
                    transferPurpose = "service_payment",
                    sourceOfFunds = "verification.source_of_funds.other"
                }
            };

            var requestMessage = new HttpRequestMessage(HttpMethod.Post, TransfersEndpoint)
            {
                Content = JsonContent.Create(request)
            };
            // Wise uses X-Idempotency-Key header? or is it customerTransactionId?
            // Wise documentation specifies customerTransactionId inside the body is used for idempotency 
            // but deduping also happens if a UUID is passed. 
            // Some endpoints support X-Idempotency-Key. We'll rely on customerTransactionId in body for v1/transfers.

            var response = await _httpClient.SendAsync(requestMessage, ct);
            await EnsureSuccessAsync(response, "Create Transfer");

            var result = await response.Content.ReadFromJsonAsync<WiseTransferResponse>(cancellationToken: ct);
            return result?.Id.ToString() ?? throw new InvalidOperationException("Failed to retrieve Transfer ID from Wise response.");
        }

        private async Task EnsureSuccessAsync(HttpResponseMessage response, string action)
        {
            if (!response.IsSuccessStatusCode)
            {
                var content = await response.Content.ReadAsStringAsync();
                _logger.LogError("Wise API {Action} failed. Status: {StatusCode}, Response: {Content}", action, response.StatusCode, content);
                throw new InvalidOperationException($"Wise API {action} failed with status {response.StatusCode}. Details: {content}");
            }
        }

        // Internal DTOs for Wise API responses
        private class WiseQuoteResponse
        {
            [JsonPropertyName("id")]
            public string Id { get; set; }
        }

        private class WiseTransferResponse
        {
            [JsonPropertyName("id")]
            public int Id { get; set; } // Wise Transfer IDs are integers (usually) or longs
        }
    }
}