using EnterpriseMediator.ProjectManagement.Domain.Aggregates.ProjectAggregate;
using EnterpriseMediator.ProjectManagement.Domain.Enums;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace EnterpriseMediator.ProjectManagement.Infrastructure.Persistence.Configurations;

/// <summary>
/// Entity Framework Core configuration for the Project Aggregate Root.
/// Handles mapping of the Project entity, its value objects, and relationships to the database schema.
/// </summary>
public class ProjectConfiguration : IEntityTypeConfiguration<Project>
{
    public void Configure(EntityTypeBuilder<Project> builder)
    {
        // Table Mapping
        builder.ToTable("Projects");

        // Primary Key
        builder.HasKey(p => p.Id);

        // Properties
        builder.Property(p => p.Id)
            .ValueGeneratedNever(); // GUIDs are typically generated by the application/domain

        builder.Property(p => p.ClientId)
            .IsRequired();

        // Enum Conversion - Store Status as string for readability and versioning safety
        builder.Property(p => p.Status)
            .HasConversion<string>()
            .HasMaxLength(50)
            .IsRequired();

        // Value Object: SowDetails (Mapped to JSONB column for flexibility with AI-extracted data)
        // This utilizes EF Core 8's native JSON column support for PostgreSQL
        builder.OwnsOne(p => p.SowDetails, sowBuilder =>
        {
            sowBuilder.ToJson();
            
            // Map individual properties within the JSON document
            // Assuming SowDetails has these properties based on domain requirements
            // If the domain model varies, these mappings would adjust dynamically
            // Note: In EF Core 8 with ToJson(), simple properties are mapped automatically,
            // but explicit configuration is good practice for documentation.
        });

        // Owned Collection: PayoutRules
        // These are financial rules tied strictly to the project lifecycle.
        // We map them to a separate table to allow for potential SQL-based reporting/summing if needed,
        // maintaining strict referential integrity for financial configuration.
        builder.OwnsMany(p => p.PayoutRules, rulesBuilder =>
        {
            rulesBuilder.ToTable("ProjectPayoutRules");
            
            rulesBuilder.WithOwner()
                .HasForeignKey("ProjectId");

            rulesBuilder.HasKey("Id"); // Shadow key or Id property on ProjectPayoutRule

            rulesBuilder.Property("Id")
                .ValueGeneratedOnAdd();

            // Configure properties of PayoutRule
            // Assuming properties like Percentage, Amount, MilestoneId, etc.
            // Example configuration:
            // rulesBuilder.Property(pr => pr.Amount).HasColumnType("decimal(18,2)");
        });

        // Relationship: Proposals
        // A Project has many Proposals. Deleting a Project should cascade to Proposals
        // as they make no sense without the parent project context in this bounded context.
        builder.HasMany(p => p.Proposals)
            .WithOne()
            .HasForeignKey("ProjectId") // Proposal.ProjectId
            .OnDelete(DeleteBehavior.Cascade);

        // Ignore DomainEvents as they are runtime artifacts, not persisted state
        builder.Ignore(p => p.DomainEvents);

        // Concurrency Token (Optional but recommended for aggregates)
        builder.Property<byte[]>("RowVersion")
            .IsRowVersion();
    }
}